model_name : Tiny_CD
dataset_name : MNCDV2
data_type : MNCD #HG is another option
dataset_path : /home/eric/datasets/MineNetCDV2_Cropped160_Step160
input_nc : 10
num_classes : 2
push_to_hub : False

train:
  epochs : 10
  batch_size : 32
  lr : 0.00356799066427741
  weight_decay: 0.009449677083344786
  loss: BCE
  snapshots_dir : ./checkpoints/
  optim : AdamW
  save_intervals : 1
eval:
  batch_size : 32
  evaluator: torchmetrics
test:
  batch_size : 32
  save_path : ./results/
