model_name : FC-EF
dataset_name : MNCDV3
data_type : MNCDV3 #HG is another option
dataset_path : /bigdata/3dabc/MNCD/MNCDV3_Bitemporal_Cropped_Size224_Step112
input_nc : 9
num_classes : 2
push_to_hub : False

train:
  epochs : 50
  batch_size : 16
  lr : 0.0001
  loss: CrossEntropy
  snapshots_dir : ./checkpoints/
  optim : Adam
  save_intervals : 1
eval :
  evaluator: torchmetrics
  batch_size : 32
test:
  batch_size : 32
  save_path : ./results/
