model_name : HANet
dataset_name : MNCDV3
data_type : MNCDV3 #HG is another option
dataset_path : /bigdata/3dabc/MNCD/MNCDV3_Bitemporal_Cropped_Size224_Step112
input_nc : 9
num_classes : 2
push_to_hub : False

train:
  epochs : 50
  batch_size : 16
  lr : 0.0001
  loss: CrossEntropy
  snapshots_dir : ./checkpoints/
  optim : AdamW
  weight_decay: 0.0005
  save_intervals : 1
eval:
  batch_size : 16
  evaluator: torchmetrics
test:
  batch_size : 16
  save_path : ./results/
